<a href="https://colab.research.google.com/github/szhang06/matrix-operation/blob/main/3_d_axis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>



> argmax



In [1]:
import numpy as np

In [16]:
# 2-dimension
a = np.array([[1,5,5,2],
               [9,-6,2,8],
               [-3,7,-9,1]])

In [17]:
b = np.argmax(a, axis = 0)
print(b) # 

[1 2 0 1]


In [19]:
c = np.argmax(a, axis = 1) # 行里比较
print(c)

[1 0 1]


In [2]:
a = np.array([[[1,5,5,2],
               [9,-6,2,8],
               [-3,7,-9,1]],
              [[-1,7,-5,2],
               [9,6,2,8],
               [3,7,9,1]],
              [[21,6,-5,2],
               [9,36,2,8],
               [3,7,79,1]]           
              ])

In [6]:
print(a.shape)

(3, 3, 4)


In [9]:
b = np.argmax(a, axis = 0)  # 先拿出行，然后按列比较
                              #先比较[1,5,5,2]，[-1,7,-5,2]，[21,6,-5,2] 列 -> [2 1 0 0]
print(b)
print(b.shape)

[[2 1 0 0]
 [0 2 0 0]
 [1 0 2 0]]
(3, 4)


三维矩阵有三个方向 0,1,2

In [10]:
b = np.argmax(a, axis = 1) #第一个矩阵按列比较，然后三个矩阵放在一起 [[1,5,5,2],
               #[9,-6,2,8],
               #[-3,7,-9,1]] -> [1,2,0,1]
print(b)
print(b.shape)

[[1 2 0 1]
 [1 0 2 1]
 [0 1 2 1]]
(3, 4)


In [11]:
b = np.argmax(a, axis = 2) # 每个矩阵行内部行比较 [[1,5,5,2],
               #[9,-6,2,8],
               #[-3,7,-9,1]] -> [1,0,1]
print(b)
print(b.shape)               

[[1 0 1]
 [1 0 2]
 [0 1 2]]
(3, 3)


In [12]:
#指定矩阵
print(np.argmax(a[0,-1,:])) # 第一个矩阵最后一行

1


In [13]:
print(np.argmax(a[1,:,2])) # 第一个矩阵第3列

2
